//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "article_category")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub article_id: u64,
	#[sea_orm(primary_key, auto_increment = false)]
	pub category_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::article::Entity",
		from = "Column::ArticleId",
		to = "super::article::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	Article,
	#[sea_orm(
		belongs_to = "super::category::Entity",
		from = "Column::CategoryId",
		to = "super::category::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	Category,
}

impl Related<super::article::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Article.def()
	}
}

impl Related<super::category::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Category.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
