//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "article_tag")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub article_id: u64,
	#[sea_orm(primary_key, auto_increment = false)]
	pub tag_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::article::Entity",
		from = "Column::ArticleId",
		to = "super::article::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Article,
	#[sea_orm(
		belongs_to = "super::tag::Entity",
		from = "Column::TagId",
		to = "super::tag::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Tag,
}

impl Related<super::article::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Article.def()
	}
}

impl Related<super::tag::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Tag.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
