//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod prelude;

pub mod article;
pub mod article_favorite;
pub mod article_tag;
pub mod casbin_rule;
pub mod category;
pub mod channel;
pub mod comment;
pub mod comment_favorite;
pub mod email;
pub mod follow;
pub mod message;
pub mod tag;
pub mod user;
pub mod user_category;
