//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub use super::article::Entity as Article;
pub use super::article_category::Entity as ArticleCategory;
pub use super::article_favorite::Entity as ArticleFavorite;
pub use super::article_tag::Entity as ArticleTag;
pub use super::casbin_rule::Entity as CasbinRule;
pub use super::category::Entity as Category;
pub use super::channel::Entity as Channel;
pub use super::comment::Entity as Comment;
pub use super::comment_favorite::Entity as CommentFavorite;
pub use super::email::Entity as Email;
pub use super::follow::Entity as Follow;
pub use super::message::Entity as Message;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
pub use super::user_category::Entity as UserCategory;
