name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  production-release:
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install auto
        run: |
          npm i -g auto
          npm i -g @auto-it/git-tag
          npm i -g @auto-it/crates
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          auto shipit
